# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: little-shop-development

test:
  adapter: postgresql
  database: little-shop-test

production:
  adapter: postgresql
  encoding: unicode
  database: little-shop-production
  pool: 2
  username: little_shop
  password: <%= ENV['LITTLE_SHOP_DATABASE_PASSWORD'] %>
